CREATE TABLE USER (
	USER_ID VARCHAR(50) PRIMARY KEY,
	PW VARCHAR(100) NOT NULL,
	USER_NAME VARCHAR(20) NOT NULL
);

CREATE TABLE MODEL(
	MODEL_ID VARCHAR(50) PRIMARY KEY,
	USER_ID VARCHAR(50),
    CLASSIFICATION BOOL,
    EPOCH TINYINT UNSIGNED,
	MODEL_DIR VARCHAR(200),
	IMAGE_WIDTH SMALLINT UNSIGNED,
	IMAGE_HEIGHT SMALLINT UNSIGNED,
    COLOR_TYPE TINYINT UNSIGNED,
	FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID)
);

CREATE TABLE IMAGE(
	MODEL_ID VARCHAR(50),
	IMAGE_DIR VARCHAR(200),
	LABEL VARCHAR(50),
	FOREIGN KEY(MODEL_ID) REFERENCES MODEL(MODEL_ID)
);

USE CUSTOM_VVISION;
INSERT INTO USER VALUES("LJH", "1234","이정협");
INSERT INTO MODEL (MODEL_ID, USER_ID) VALUES ("MODELID", "LJH");
INSERT INTO MODEL (MODEL_ID, USER_ID) VALUES ("2222", "LJH");
INSERT INTO MODEL (MODEL_ID, USER_ID) VALUES ("3333", "LJH");
INSERT INTO MODEL (MODEL_ID, USER_ID, IMAGE_WIDTH, IMAGE_HEIGHT) VALUES ("4444", "LJH",28,28);


DROP TABLE IMAGE;
DROP TABLE MODEL;
DROP TABLE USER;

SELECT * FROM USER;