CREATE TABLE USER (
	USER_ID VARCHAR(50) PRIMARY KEY,
	PW VARCHAR(100) NOT NULL,
	USER_NAME VARCHAR(20) NOT NULL
);

CREATE TABLE MODEL(
	MODEL_ID VARCHAR(50) PRIMARY KEY,
	USER_ID VARCHAR(50),
	MODEL_DIR VARCHAR(200) NOT NULL,
	IMAGE_WIDTH SMALLINT UNSIGNED NOT NULL,
	IMAGE_HEIGHT SMALLINT UNSIGNED NOT NULL,
	FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID)
);

CREATE TABLE IMAGE(
	MODEL_ID VARCHAR(50),
	IMAGE_DIR VARCHAR(200) NOT NULL,
	LABEL VARCHAR(50) NOT NULL,
	FOREIGN KEY(MODEL_ID) REFERENCES MODEL(MODEL_ID)
);